services:
  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    networks:
      - symfony

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - symfony

  postgres:
    container_name: postgres_full_stack_dev
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - symfony

  pgAdmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin4_full_stack_dev
    ports:
      - "15432:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    depends_on:
      - postgres

networks:
  symfony:
