version: '3.8'

services:
  postgres:
    restart: always
    image: postgres
    user: "1000:1000"
    container_name: "postgresFullStack"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - postgres

  php:
    container_name: "php-fpm"
    build:
      context: ./docker/php
      args:
        PHP_VERSION: 8.2
    environment:
      # Symfony Config
      - APP_ENV=dev
      - APP_SECRET=your_app_secret
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0
      - APP_DEBUG=true
    volumes:
      - ./:/var/www

  nginx:
    container_name: "nginx"
    environment:
      HOSTNAME: 127.0.0.1
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "80:80"
